Add FreeBSD support
AravisProject/aravis pull request #620
Opened 2022-01-11 12:38 UTC by rozhuk-im

Add FreeBSD support and probably fix other OSes to not show network interfaces without BROADCAST flag.

2022-01-11 13:49 UTC, rozhuk-im commented
Have no idea why Linux and MSVC fail, looks like some temporary errors in test system.

2022-01-11 22:15 UTC, rozhuk-im commented
After I disable ```if ((ifap_iter->ifa_flags & IFF_BROADCAST) == 0)``` test is passed, but IMHO this is wrong, and interfaces without broadcast flag must not be used.

2022-01-12 06:08 UTC, EmmanuelP requested changes
Thanks for the patch. Once the commented code is removed, it will be ready to merge.

2022-01-12 06:08 UTC, EmmanuelP commented on src/arvnetwork.c
> +//#endif
Please remove this part of commented code.

2022-01-12 06:11 UTC, EmmanuelP commented
> After I disable `if ((ifap_iter->ifa_flags & IFF_BROADCAST) == 0)` test is passed, but IMHO this is wrong, and interfaces without broadcast flag must not be used.

That is not really related to the main goal of this pull request, so the pull request can be merged without this part. But feel free to investigate why this test makes the fakegv test fail on linux and macOS in another pull request.

2022-01-13 07:16 UTC, EmmanuelP requested changes

2022-01-13 07:16 UTC, EmmanuelP commented on src/arvnetworkprivate.h
> +#include <netinet/ip.h>
Redundant include.

2022-01-13 07:59 UTC, merged

2022-01-13 10:11 UTC, EmmanuelP commented
Thanks a lot.