Fix crash when using stream callback in Python
AravisProject/aravis pull request #714
Opened 2022-09-09 13:27 UTC by lostcontrol

This PR should fix the crash seen in #453. The crash was caused by `ArvStreamCallback` only living for the time of the call to `arv_camera_create_stream` because of `(scope call)`. Using `(scope notified)` allows us to control the lifetime of the callback.

Also added a small Python sample showing how to use stream callback.

:warning: GObject & GLib noob here, careful review required.

2022-09-09 13:36 UTC, lostcontrol commented
Applying `clang-format` to the files results in many unrelated changes. It seems also like there is a mix of tabs and spaces already.

I didn't write any tests. Should I extend `tests/fake.py` to also use a callback?

2022-09-09 13:45 UTC, EmmanuelP commented
> Applying `clang-format` to the files results in many unrelated changes. It seems also like there is a mix of tabs and spaces already.

Don't bother about clang-format. I should remove it from the repository.

> I didn't write any tests. Should I extend `tests/fake.py` to also use a callback?

That would be nice, yes.

2022-09-09 13:55 UTC, EmmanuelP requested changes
Looks fine.

The ArvDevice::create_stream signature change is an API break, but adding a new create_stream_full would still be an ABI break. ArvDevice virtual methods are not really meant to be public, so your change is fine.

2022-09-09 13:55 UTC, EmmanuelP commented on src/arvdevice.c
> + * Since: 0.2.0
Since 0.8.23

2022-09-12 11:49 UTC, lostcontrol commented on src/arvcamera.c
> + * Since: 0.2.0
Done

2022-09-12 11:49 UTC, lostcontrol commented on src/arvdevice.c
> + * Since: 0.2.0
Done

2022-09-12 12:07 UTC, lostcontrol commented
I also quickly tested with a Lucid TRI064S-M. Seems to work fine.

2022-09-12 12:48 UTC, EmmanuelP commented
Thanks a lot Cyril. Everything looks fine now.

I'm still a bit worried about the ABI break. So before merging these changes, I have to check what was the ABI stability of Aravis during the 0.8 series, and see if this sort of breakage already happened. If not, I will probably switch to a new series. It may take a couple of weeks.

2022-09-20 19:27 UTC, merged

2022-09-20 19:33 UTC, EmmanuelP commented
It already happened in the 0.8 series a class definition has changed, so let's commit these changes.

Subclassing Aravis classes is not really supported. It should be made more clear by either making most of the class definition private (which would still allow subclassing, but will not permit to overwrite the virtual functions), or by simply moving the class definition in the private headers. That will not happen in the 0.8 series though.

Thanks a lot for your work on this issue. I had a look several time at it without success.

Cheers.

2022-09-20 20:07 UTC, bpinsard commented
Thanks a lot for the fix to both a you, just tested it and works perfectly. Will close the issue.

2022-09-23 12:36 UTC, lostcontrol commented
Thank you for your feedback. By the way, [Asyril SA](http://www.asyril.com), my employer, "sponsored" this fix by letting me work on it during my working time.