Frame rate limit disabling also need vendor specific quirks
AravisProject/aravis pull request #769
Opened 2023-02-27 09:23 UTC by durnezj

Hi,

I have the following fixes running successfully in my project as a patch and am now proposing to add these upstream so they can be included in a future release (and I can just update my buildroot's Aravis version).

This PR fixes the following:
- Vendor specific quirks to set the frame rate limit were only checked when frame rate limiting must be enabled.
- When wanting to disable frame rate limiting by calling arv_camera_set_frame_rate(cam,  **0**, NULL), the vendor specific quirks were not applied.
- This was observed on a FLIR and Basler camera, where the Basler works out of the box, but the the FLIR one needed the quirk to disable frame rate limiting.

I have proposed to fix this by extracting the code with the vendor specific quirks to a new method arv_camera_set_frame_rate_enable(cam, TRUE/FALSE, GError) that encapsulates this, and then call this in arv_camera_set_frame_rate().

(Now that I think of it, it migh be good to provide a arv_camera_get_frame_rate_enable() as well?)

As it's my first time working with the GLib 'flow' and Aravis internals, please verify if everything is up to standards regarding code style, error handling,...

Kind regards,
Durnezj

2023-03-07 18:45 UTC, durnezj commented
I seem to have overlooked some leftover debug printf statements, will clean them up!

2023-03-10 07:35 UTC, EmmanuelP requested changes
Thanks for the patch.

It looks good, baring the function name.

2023-03-10 07:35 UTC, EmmanuelP commented on src/arvcamera.c
> +* arv_camera_set_frame_rate_enabled:
The feature name in Genicam SFNC is AcquisitionFrameRateEnable. Please rename the function to arv_camera_set_frame_rate_enable.

2023-03-10 08:55 UTC, merged

2023-03-10 09:16 UTC, durnezj commented
Thanks for accepting the fix! :smile: